springdoc:
  api-docs:
    path: /openapi

server:
  port: 3000

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/static/

  web:
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,env,configprops,loggers,threaddump,heapdump,mappings
  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized
  info:
    env:
      enabled: true